// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <R_ext/Visibility.h>
#include <Rcpp.h>

using namespace Rcpp;

// rgl2pdf3d
CharacterVector rgl2pdf3d_conv(CharacterVector filename, List scene3d, bool writepdf, bool writeprc, bool writevws, bool writejs);

RcppExport SEXP attribute_visible rgl2pdf3d_rgl2pdf3d(SEXP filenameSEXP, SEXP scene3dSEXP, SEXP writepdfSEXP, SEXP writeprcSEXP, SEXP writevwsSEXP, SEXP writejsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    CharacterVector filename = Rcpp::as<CharacterVector >(filenameSEXP);
    List scene3d = Rcpp::as<List >(scene3dSEXP);
    bool writepdf = Rcpp::as<bool >(writepdfSEXP);
    bool writeprc = Rcpp::as<bool >(writeprcSEXP);
    bool writevws = Rcpp::as<bool >(writevwsSEXP);
    bool writejs  = Rcpp::as<bool >(writejsSEXP);
    CharacterVector __result = rgl2pdf3d_conv(filename, scene3d, writepdf, writeprc, writevws, writejs);
    return Rcpp::wrap(__result);
END_RCPP
}
