# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rgl2pdf3d <- function(basefilename, writepdf=TRUE, writeprc=FALSE, writevws=FALSE, writejs=FALSE) {
    .Call('rgl2pdf3d_rgl2pdf3d', PACKAGE = 'rgl2pdf3d', basefilename, scene3d(), writepdf, writeprc, writevws, writejs)
}
